{
 "title": "Moss Ne3s System Program Report - KPI",
 "tags": [ "radio" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "edgeName",
    "label": "Edge Instance",
    "query": "{\"find\": \"terms\", \"field\": \"edgename.keyword\"}"
   },
   {
    "name": "ne_aliasName",
    "label": "EnodeB Alias Name",
    "query": "{\"find\": \"terms\", \"field\": \"nename.keyword\", \"query\":\"edgename:$edgeName\"}"
   },
   {
    "name": "ObjectType",
    "label": "ObjectType",
    "query": "{\"find\": \"terms\", \"field\": \"ObjectType.keyword\"}"
   },
   {
    "name": "Dn",
    "label": "Dn",
    "query": "{\"find\": \"terms\", \"field\": \"Dn.keyword\"}"
   },
   { "name": "dataSource", "label": "Data Source", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "E-UTRAN Cell Availability Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_Cell_Avail_M8020C3",
       "id": "1",
       "inlineScript": "(doc.LTE_Cell_Avail_M8020C3.value/doc.LTE_Cell_Avail_M8020C6.value)*100",
       "meta": {},
       "settings": {
        "script": {
         "inline": "(doc.LTE_Cell_Avail_M8020C3.value/doc.LTE_Cell_Avail_M8020C6.value)*100"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn AND -LTE_Cell_Avail_M8020C6:0",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN Cell Availability, excluding blocked by user state (BLU)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_Cell_Avail_M8020C3",
       "id": "1",
       "inlineScript": "100*(doc.LTE_Cell_Avail_M8020C3.value)/(doc.LTE_Cell_Avail_M8020C6.value - doc.LTE_Cell_Avail_M8020C4.value - doc.LTE_Cell_Avail_M8020C7.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100*(doc.LTE_Cell_Avail_M8020C3.value)/(doc.LTE_Cell_Avail_M8020C6.value - doc.LTE_Cell_Avail_M8020C4.value - doc.LTE_Cell_Avail_M8020C7.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN RACH Setup Attempts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_Cell_Load_M8001C6",
       "id": "1",
       "inlineScript": "(doc.LTE_Cell_Load_M8001C6.value+doc.LTE_Cell_Load_M8001C7.value+doc.LTE_Cell_Load_M8001C286.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "(doc.LTE_Cell_Load_M8001C6.value+doc.LTE_Cell_Load_M8001C7.value+doc.LTE_Cell_Load_M8001C286.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN RACH Setup Completion Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_Cell_Load_M8001C8",
       "id": "1",
       "inlineScript": "100* (doc.LTE_Cell_Load_M8001C8.value)/(doc.LTE_Cell_Load_M8001C6.value+doc.LTE_Cell_Load_M8001C7.value+doc.LTE_Cell_Load_M8001C286.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100* (doc.LTE_Cell_Load_M8001C8.value)/(doc.LTE_Cell_Load_M8001C6.value+doc.LTE_Cell_Load_M8001C7.value+doc.LTE_Cell_Load_M8001C286.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN Complete Contention Based RACH Setup Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_MAC_M8029C32",
       "id": "1",
       "inlineScript": "100* (doc.LTE_MAC_M8029C32.value)/(doc.LTE_Cell_Load_M8001C6.value+doc.LTE_Cell_Load_M8001C7.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100* (doc.LTE_MAC_M8029C32.value)/(doc.LTE_Cell_Load_M8001C6.value+doc.LTE_Cell_Load_M8001C7.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total E-UTRAN RRC Connection Setup Attempts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_UE_State_M8013C17",
       "id": "1",
       "inlineScript": "(doc.LTE_UE_State_M8013C17.value +doc.LTE_UE_State_M8013C18.value + doc.LTE_UE_State_M8013C19.value + doc.LTE_UE_State_M8013C34.value + doc.LTE_UE_State_M8013C31.value + doc.LTE_UE_State_M8013C21.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "(doc.LTE_UE_State_M8013C17.value +doc.LTE_UE_State_M8013C18.value + doc.LTE_UE_State_M8013C19.value + doc.LTE_UE_State_M8013C34.value + doc.LTE_UE_State_M8013C31.value + doc.LTE_UE_State_M8013C21.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total E-UTRAN RRC Connection Setup Success Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_UE_State_M8013C5",
       "id": "1",
       "inlineScript": "100*(doc.LTE_UE_State_M8013C5.value) / (doc.LTE_UE_State_M8013C17.value +doc.LTE_UE_State_M8013C18.value + doc.LTE_UE_State_M8013C19.value + doc.LTE_UE_State_M8013C34.value + doc.LTE_UE_State_M8013C31.value + doc.LTE_UE_State_M8013C21.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100*(doc.LTE_UE_State_M8013C5.value) / (doc.LTE_UE_State_M8013C17.value +doc.LTE_UE_State_M8013C18.value + doc.LTE_UE_State_M8013C19.value + doc.LTE_UE_State_M8013C34.value + doc.LTE_UE_State_M8013C31.value + doc.LTE_UE_State_M8013C21.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN UE Transaction to ECM-IDLE State Success Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_UE_State_M8013C13",
       "id": "1",
       "inlineScript": "100*(doc.LTE_UE_State_M8013C13.value + doc.LTE_UE_State_M8013C10.value+ doc.LTE_UE_State_M8013C9.value +doc.LTE_UE_State_M8013C82.value + doc.LTE_Inter_Sys_HO_M8016C23.value +doc.LTE_Inter_Sys_HO_M8016C30.value + doc.LTE_Inter_Sys_HO_M8016C34.value)/ (doc.LTE_UE_State_M8013C13.value + doc.LTE_UE_State_M8013C12.value + doc.LTE_UE_State_M8013C15.value+ doc.LTE_UE_State_M8013C10.value +doc.LTE_UE_State_M8013C12.value+ doc.LTE_UE_State_M8013C15.value+ doc.LTE_UE_State_M8013C9.value +doc.LTE_UE_State_M8013C28.value + doc.LTE_Inter_Sys_HO_M8016C23.value +doc.LTE_Inter_Sys_HO_M8016C30.value + doc.LTE_Inter_Sys_HO_M8016C34.value + doc.LTE_UE_State_M8013C77.value +doc.LTE_UE_State_M8013C78.value+doc.LTE_UE_State_M8013C79.value + doc.LTE_UE_State_M8013C80.value + doc.LTE_UE_State_M8013C81.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100*(doc.LTE_UE_State_M8013C13.value + doc.LTE_UE_State_M8013C10.value+ doc.LTE_UE_State_M8013C9.value +doc.LTE_UE_State_M8013C82.value + doc.LTE_Inter_Sys_HO_M8016C23.value +doc.LTE_Inter_Sys_HO_M8016C30.value + doc.LTE_Inter_Sys_HO_M8016C34.value)/ (doc.LTE_UE_State_M8013C13.value + doc.LTE_UE_State_M8013C12.value + doc.LTE_UE_State_M8013C15.value+ doc.LTE_UE_State_M8013C10.value +doc.LTE_UE_State_M8013C12.value+ doc.LTE_UE_State_M8013C15.value+ doc.LTE_UE_State_M8013C9.value +doc.LTE_UE_State_M8013C28.value + doc.LTE_Inter_Sys_HO_M8016C23.value +doc.LTE_Inter_Sys_HO_M8016C30.value + doc.LTE_Inter_Sys_HO_M8016C34.value + doc.LTE_UE_State_M8013C77.value +doc.LTE_UE_State_M8013C78.value+doc.LTE_UE_State_M8013C79.value + doc.LTE_UE_State_M8013C80.value + doc.LTE_UE_State_M8013C81.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total E-UTRAN RRC Connection Re-establishment Success Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_RRC_M8008C5",
       "id": "1",
       "inlineScript": "100*(doc.LTE_RRC_M8008C5.value/doc.LTE_RRC_M8008C4.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100*(doc.LTE_RRC_M8008C5.value/doc.LTE_RRC_M8008C4.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "-LTE_RRC_M8008C5:0 AND edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "RRC Connection Re-establishment Attempts per type total attempts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_RRC_M8008C4",
       "id": "1",
       "inlineScript": "doc.LTE_RRC_M8008C4.value",
       "meta": {},
       "settings": { "script": { "inline": "doc.LTE_RRC_M8008C4.value" } },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN Discarded RRC Paging Records",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_RRC_M8008C2",
       "id": "1",
       "inlineScript": "doc.LTE_RRC_M8008C2.value",
       "meta": {},
       "settings": { "script": { "inline": "doc.LTE_RRC_M8008C2.value" } },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN RRC Paging Records",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_RRC_M8008C1",
       "id": "1",
       "inlineScript": "doc.LTE_RRC_M8008C1.value",
       "meta": {},
       "settings": { "script": { "inline": "doc.LTE_RRC_M8008C1.value" } },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN Data Radio Bearer Attempts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_Radio_Bearer_M8007C0",
       "id": "1",
       "inlineScript": "doc.LTE_Radio_Bearer_M8007C0.value",
       "meta": {},
       "settings": {
        "script": {
         "inline": "doc.LTE_Radio_Bearer_M8007C0.value"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN Data Radio Bearer Setup Success Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_Radio_Bearer_M8007C1",
       "id": "1",
       "inlineScript": "100*(doc.LTE_Radio_Bearer_M8007C1.value/ doc.LTE_Radio_Bearer_M8007C0.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100*(doc.LTE_Radio_Bearer_M8007C1.value/ doc.LTE_Radio_Bearer_M8007C0.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "-LTE_Radio_Bearer_M8007C0:0 AND edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN Radio Bearer Success Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_EPS_Bearer_M8006C261",
       "id": "1",
       "inlineScript": "100 - 100*(doc.LTE_EPS_Bearer_M8006C261.value +doc.LTE_EPS_Bearer_M8006C254.value - doc.LTE_EPS_Bearer_M8006C255.value - doc.LTE_EPS_Bearer_M8006C258.value + doc.LTE_EPS_Bearer_M8006C8.value + doc.LTE_EPS_Bearer_M8006C9.value+ doc.LTE_EPS_Bearer_M8006C277.value] - doc.LTE_EPS_Bearer_M8006C301.value - doc.LTE_EPS_Bearer_M8006C314.value + doc.LTE_EPS_Bearer_M8006C309.value+ doc.LTE_EPS_Bearer_M8006C310.value + doc.LTE_EPS_Bearer_M8006C311.value + doc.LTE_EPS_Bearer_M8006C312.value + doc.LTE_EPS_Bearer_M8006C313.value)/(doc.LTE_EPS_Bearer_M8006C254.value + doc.LTE_EPS_Bearer_M8006C263.value + doc.LTE_EPS_Bearer_M8006C261.value + doc.LTE_EPS_Bearer_M8006C6.value + doc.LTE_EPS_Bearer_M8006C7.value + doc.LTE_EPS_Bearer_M8006C8.value + doc.LTE_EPS_Bearer_M8006C9.value + doc.LTE_EPS_Bearer_M8006C277.value - doc.LTE_EPS_Bearer_M8006C301.value + doc.LTE_EPS_Bearer_M8006C303.value +doc.LTE_EPS_Bearer_M8006C306.value + doc.LTE_EPS_Bearer_M8006C309.value + doc.LTE_EPS_Bearer_M8006C310.value + doc.LTE_EPS_Bearer_M8006C311.value + doc.LTE_EPS_Bearer_M8006C312.value + doc.LTE_EPS_Bearer_M8006C313.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100 - 100*(doc.LTE_EPS_Bearer_M8006C261.value +doc.LTE_EPS_Bearer_M8006C254.value - doc.LTE_EPS_Bearer_M8006C255.value - doc.LTE_EPS_Bearer_M8006C258.value + doc.LTE_EPS_Bearer_M8006C8.value + doc.LTE_EPS_Bearer_M8006C9.value+ doc.LTE_EPS_Bearer_M8006C277.value] - doc.LTE_EPS_Bearer_M8006C301.value - doc.LTE_EPS_Bearer_M8006C314.value + doc.LTE_EPS_Bearer_M8006C309.value+ doc.LTE_EPS_Bearer_M8006C310.value + doc.LTE_EPS_Bearer_M8006C311.value + doc.LTE_EPS_Bearer_M8006C312.value + doc.LTE_EPS_Bearer_M8006C313.value)/(doc.LTE_EPS_Bearer_M8006C254.value + doc.LTE_EPS_Bearer_M8006C263.value + doc.LTE_EPS_Bearer_M8006C261.value + doc.LTE_EPS_Bearer_M8006C6.value + doc.LTE_EPS_Bearer_M8006C7.value + doc.LTE_EPS_Bearer_M8006C8.value + doc.LTE_EPS_Bearer_M8006C9.value + doc.LTE_EPS_Bearer_M8006C277.value - doc.LTE_EPS_Bearer_M8006C301.value + doc.LTE_EPS_Bearer_M8006C303.value +doc.LTE_EPS_Bearer_M8006C306.value + doc.LTE_EPS_Bearer_M8006C309.value + doc.LTE_EPS_Bearer_M8006C310.value + doc.LTE_EPS_Bearer_M8006C311.value + doc.LTE_EPS_Bearer_M8006C312.value + doc.LTE_EPS_Bearer_M8006C313.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN E-RAB Setup Attempts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_EPS_Bearer_M8006C0",
       "id": "1",
       "inlineScript": "doc.LTE_EPS_Bearer_M8006C0.value",
       "meta": {},
       "settings": {
        "script": {
         "inline": "doc.LTE_EPS_Bearer_M8006C0.value"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN E-RAB Setup Success Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_EPS_Bearer_M8006C1",
       "id": "1",
       "inlineScript": "100*(doc.LTE_EPS_Bearer_M8006C1.value / doc.LTE_EPS_Bearer_M8006C0.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100*(doc.LTE_EPS_Bearer_M8006C1.value / doc.LTE_EPS_Bearer_M8006C0.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "-LTE_EPS_Bearer_M8006C0:0 AND edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN E-RAB Normal Release Ratio User Perspective",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_EPS_Bearer_M8006C255",
       "id": "1",
       "inlineScript": "100*(doc.LTE_EPS_Bearer_M8006C255.value + doc.LTE_EPS_Bearer_M8006C258.value + doc.LTE_EPS_Bearer_M8006C6.value + doc.LTE_EPS_Bearer_M8006C7.value + doc.LTE_EPS_Bearer_M8006C303.value + doc.LTE_EPS_Bearer_M8006C306.value + doc.LTE_EPS_Bearer_M8006C314.value)/(doc.LTE_EPS_Bearer_M8006C254.value +doc.LTE_EPS_Bearer_M8006C261.value+ doc.LTE_EPS_Bearer_M8006C6.value + doc.LTE_EPS_Bearer_M8006C7.value+ doc.LTE_EPS_Bearer_M8006C8.value + doc.LTE_EPS_Bearer_M8006C9.value + doc.LTE_EPS_Bearer_M8006C277.value- doc.LTE_EPS_Bearer_M8006C301.value + doc.LTE_EPS_Bearer_M8006C303.value+doc.LTE_EPS_Bearer_M8006C306.value+ doc.LTE_EPS_Bearer_M8006C309.value+ doc.LTE_EPS_Bearer_M8006C310.value + doc.LTE_EPS_Bearer_M8006C311.value + doc.LTE_EPS_Bearer_M8006C312.value +doc.LTE_EPS_Bearer_M8006C313.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100*(doc.LTE_EPS_Bearer_M8006C255.value + doc.LTE_EPS_Bearer_M8006C258.value + doc.LTE_EPS_Bearer_M8006C6.value + doc.LTE_EPS_Bearer_M8006C7.value + doc.LTE_EPS_Bearer_M8006C303.value + doc.LTE_EPS_Bearer_M8006C306.value + doc.LTE_EPS_Bearer_M8006C314.value)/(doc.LTE_EPS_Bearer_M8006C254.value +doc.LTE_EPS_Bearer_M8006C261.value+ doc.LTE_EPS_Bearer_M8006C6.value + doc.LTE_EPS_Bearer_M8006C7.value+ doc.LTE_EPS_Bearer_M8006C8.value + doc.LTE_EPS_Bearer_M8006C9.value + doc.LTE_EPS_Bearer_M8006C277.value- doc.LTE_EPS_Bearer_M8006C301.value + doc.LTE_EPS_Bearer_M8006C303.value+doc.LTE_EPS_Bearer_M8006C306.value+ doc.LTE_EPS_Bearer_M8006C309.value+ doc.LTE_EPS_Bearer_M8006C310.value + doc.LTE_EPS_Bearer_M8006C311.value + doc.LTE_EPS_Bearer_M8006C312.value +doc.LTE_EPS_Bearer_M8006C313.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN E-RAB Normal Release Ratio RAN View",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_EPS_Bearer_M8006C255",
       "id": "1",
       "inlineScript": "100*(doc.LTE_EPS_Bearer_M8006C255.value + doc.LTE_EPS_Bearer_M8006C258.value+ doc.LTE_EPS_Bearer_M8006C260.value + doc.LTE_EPS_Bearer_M8006C6.value+ doc.LTE_EPS_Bearer_M8006C7.value + doc.LTE_EPS_Bearer_M8006C8.value +doc.LTE_EPS_Bearer_M8006C9.value+ doc.LTE_EPS_Bearer_M8006C277.value + doc.LTE_EPS_Bearer_M8006C10.value + doc.LTE_EPS_Bearer_M8006C12.value +doc.LTE_EPS_Bearer_M8006C303.value + doc.LTE_EPS_Bearer_M8006C306.value)/(doc.LTE_EPS_Bearer_M8006C254.value + doc.LTE_EPS_Bearer_M8006C261.value+ doc.LTE_EPS_Bearer_M8006C6.value + doc.LTE_EPS_Bearer_M8006C7.value+ doc.LTE_EPS_Bearer_M8006C8.value + doc.LTE_EPS_Bearer_M8006C9.value + doc.LTE_EPS_Bearer_M8006C277.value - doc.LTE_EPS_Bearer_M8006C301.value + doc.LTE_EPS_Bearer_M8006C303.value + doc.LTE_EPS_Bearer_M8006C306.value+ doc.LTE_EPS_Bearer_M8006C309.value + doc.LTE_EPS_Bearer_M8006C310.value + doc.LTE_EPS_Bearer_M8006C11.value + doc.LTE_EPS_Bearer_M8006C12.value + doc.LTE_EPS_Bearer_M8006C313.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100*(doc.LTE_EPS_Bearer_M8006C255.value + doc.LTE_EPS_Bearer_M8006C258.value+ doc.LTE_EPS_Bearer_M8006C260.value + doc.LTE_EPS_Bearer_M8006C6.value+ doc.LTE_EPS_Bearer_M8006C7.value + doc.LTE_EPS_Bearer_M8006C8.value +doc.LTE_EPS_Bearer_M8006C9.value+ doc.LTE_EPS_Bearer_M8006C277.value + doc.LTE_EPS_Bearer_M8006C10.value + doc.LTE_EPS_Bearer_M8006C12.value +doc.LTE_EPS_Bearer_M8006C303.value + doc.LTE_EPS_Bearer_M8006C306.value)/(doc.LTE_EPS_Bearer_M8006C254.value + doc.LTE_EPS_Bearer_M8006C261.value+ doc.LTE_EPS_Bearer_M8006C6.value + doc.LTE_EPS_Bearer_M8006C7.value+ doc.LTE_EPS_Bearer_M8006C8.value + doc.LTE_EPS_Bearer_M8006C9.value + doc.LTE_EPS_Bearer_M8006C277.value - doc.LTE_EPS_Bearer_M8006C301.value + doc.LTE_EPS_Bearer_M8006C303.value + doc.LTE_EPS_Bearer_M8006C306.value+ doc.LTE_EPS_Bearer_M8006C309.value + doc.LTE_EPS_Bearer_M8006C310.value + doc.LTE_EPS_Bearer_M8006C11.value + doc.LTE_EPS_Bearer_M8006C12.value + doc.LTE_EPS_Bearer_M8006C313.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "E-UTRAN E-RAB Drop Ratio, RAN View",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "nename.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "Dn.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "LTE_EPS_Bearer_M8006C261",
       "id": "1",
       "inlineScript": "100*(doc.LTE_EPS_Bearer_M8006C261.value + doc.LTE_EPS_Bearer_M8006C254.value- doc.LTE_EPS_Bearer_M8006C255.value - doc.LTE_EPS_Bearer_M8006C258.value - doc.LTE_EPS_Bearer_M8006C260.value -doc.LTE_EPS_Bearer_M8006C301.value+ doc.LTE_EPS_Bearer_M8006C309.value+ doc.LTE_EPS_Bearer_M8006C311.value + doc.LTE_EPS_Bearer_M8006C313.value)/(doc.LTE_EPS_Bearer_M8006C254.value + doc.LTE_EPS_Bearer_M8006C261.value + doc.LTE_EPS_Bearer_M8006C6.value + doc.LTE_EPS_Bearer_M8006C7.value +doc.LTE_EPS_Bearer_M8006C8.value + doc.LTE_EPS_Bearer_M8006C9.value+ doc.LTE_EPS_Bearer_M8006C277.value- doc.LTE_EPS_Bearer_M8006C301.value+doc.LTE_EPS_Bearer_M8006C303.value + doc.LTE_EPS_Bearer_M8006C306.value + doc.LTE_EPS_Bearer_M8006C309.value + doc.LTE_EPS_Bearer_M8006C310.value+ doc.LTE_EPS_Bearer_M8006C311.value + doc.LTE_EPS_Bearer_M8006C312.value+ doc.LTE_EPS_Bearer_M8006C313.value)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "100*(doc.LTE_EPS_Bearer_M8006C261.value + doc.LTE_EPS_Bearer_M8006C254.value- doc.LTE_EPS_Bearer_M8006C255.value - doc.LTE_EPS_Bearer_M8006C258.value - doc.LTE_EPS_Bearer_M8006C260.value -doc.LTE_EPS_Bearer_M8006C301.value+ doc.LTE_EPS_Bearer_M8006C309.value+ doc.LTE_EPS_Bearer_M8006C311.value + doc.LTE_EPS_Bearer_M8006C313.value)/(doc.LTE_EPS_Bearer_M8006C254.value + doc.LTE_EPS_Bearer_M8006C261.value + doc.LTE_EPS_Bearer_M8006C6.value + doc.LTE_EPS_Bearer_M8006C7.value +doc.LTE_EPS_Bearer_M8006C8.value + doc.LTE_EPS_Bearer_M8006C9.value+ doc.LTE_EPS_Bearer_M8006C277.value- doc.LTE_EPS_Bearer_M8006C301.value+doc.LTE_EPS_Bearer_M8006C303.value + doc.LTE_EPS_Bearer_M8006C306.value + doc.LTE_EPS_Bearer_M8006C309.value + doc.LTE_EPS_Bearer_M8006C310.value+ doc.LTE_EPS_Bearer_M8006C311.value + doc.LTE_EPS_Bearer_M8006C312.value+ doc.LTE_EPS_Bearer_M8006C313.value)"
        }
       },
       "type": "avg"
      }
     ],
     "query": "edgename:$edgeName AND nename:$ne_aliasName AND ObjectType:$ObjectType AND Dn:$Dn",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}